### ISSUE TITLE
streamlit app not working

### ISSUE THREAD

**Issue by HaraldMelin** [Ceyron/numeric-notes#20]
Hi!

I checked out your streamlit app https://englishprobabilistic-machine-learningelbo-interactive--or5u7m.streamlit.app/ which is linked in the description of this video: https://www.youtube.com/watch?v=HxQ94L8n0vU

It ran smoothly when I tried it a couple of months ago, but I've tried running it several times this week and it doesn't work anymore in neither Firefox or Chrome.

Great interactive tool and great videos you are making!

**Comment by Ceyron** [comment]
Hi,

Thanks for the issue. It turned out that the `requirements.txt` was outdated and caused some incompatibilities. I fixed it in #21. It should work again.

And also, thanks for the kind words 😊. It's amazing to see that the content found its way back to KTH, where I first learned about this stuff.

**Comment by HaraldMelin** [comment]
Nice to hear you were at KTH too! Was it perhaps the DD2434 course that
introduced you to VI? I am a TA in the course and wanted to share your tool
with the students, if you don't mind?

**Comment by Ceyron** [comment]
Yes, this was the course I took :+1: (back in fall term of 2020).

Sure, feel free to share it. :)
